name: Terraform CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:   # allows manual trigger

jobs:
  terraform:
    name: Terraform Pipeline
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev   # change per env

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check AWS Identity
        run: aws sts get-caller-identity


      - name: Terraform Init (Remote Backend)
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      # Optional Apply (Manual or Controlled)
      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve
